// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhl1NugbGh1TUB0wzCI1NQ2rXtHkq5ZVQ',
    appId: '1:456526339950:web:32f13166c6fcdea41c6b7f',
    messagingSenderId: '456526339950',
    projectId: 'lezzat',
    authDomain: 'lezzat.firebaseapp.com',
    storageBucket: 'lezzat.appspot.com',
    measurementId: 'G-ZKRYRNFXQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOR14rd7kTnBztUtaCdEezJWSkqflV8qs',
    appId: '1:456526339950:android:602a92d9dcc356cb1c6b7f',
    messagingSenderId: '456526339950',
    projectId: 'lezzat',
    storageBucket: 'lezzat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNgUyLcRd0qA8jVebVZLwlJ6b7h7g5Pg',
    appId: '1:456526339950:ios:c29e9da0b6362bae1c6b7f',
    messagingSenderId: '456526339950',
    projectId: 'lezzat',
    storageBucket: 'lezzat.appspot.com',
    iosClientId: '456526339950-ermk481k3haaoc6j8lu7he1u0vgidmd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasProject11pplg1s1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNgUyLcRd0qA8jVebVZLwlJ6b7h7g5Pg',
    appId: '1:456526339950:ios:c29e9da0b6362bae1c6b7f',
    messagingSenderId: '456526339950',
    projectId: 'lezzat',
    storageBucket: 'lezzat.appspot.com',
    iosClientId: '456526339950-ermk481k3haaoc6j8lu7he1u0vgidmd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasProject11pplg1s1',
  );
}
